### ISSUE TITLE
Remove commit() concept in favor of array set?

### ISSUE THREAD

**Issue by jleaders** [Ghostff/Session#4]
Forgive the stylistic issue, but by using 
```
change
change
change
commit
```
pattern as you set the values, someone may forget to commit() -- especially since the default PHP $_SESSION handler has no "commit" concept. (I'm aware many ORM's do, however)

Obviously it exists for performance/locking reasons, but a simple way around this is to require the set to be done via an array, for example in another [library](https://duncan3dc.github.io/sessions/) :

```
$session->set([
    "customer-name" =>  "Volition",
    "last-accessed" =>  time(),
    "location"      =>  "Skies",
]);
```
No commit() call is necessary here.

This is more of a stylistic thing, but it also prevents programmer error

**Comment by Ghostff** [comment]
I implemented an auto commit functionality , which dosn't violate the non-blocking concept. If you think that's not enough, you can send a PR.

**Comment by jleaders** [comment]
Thank you
