### ISSUE TITLE
How to configure it?

### ISSUE THREAD

**Issue by SaphiLC** [Ghostff/Session#5]
im not very good at static classes so i have no idea how to add my own configuration...not sure where to ask

**Comment by Ghostff** [comment]
I will try to make a walk through.

**Comment by Ghostff** [comment]
I made a room here https://chat.stackoverflow.com/rooms/156228/ghostff

**Comment by SaphiLC** [comment]
says i need 20 reputation to chat there ._. just created an account

**Comment by Ghostff** [comment]
https://gitter.im/ghostff/Lobby#
